const nodemailer = require('nodemailer');

/**
 * emailService.js
 * Centralized Email Automation Engine for Mahadev Co-operative Society
 * Supports Gmail, Custom Domain SMTP (Brevo, Zoho, Google Workspace), and graceful Mock mode.
 */

// Initialize SMTP Transporter
const getTransporter = () => {
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASS ? process.env.EMAIL_PASS.replace(/\s+/g, '') : '';
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT) || 587;
  const secure = process.env.SMTP_SECURE === 'true' || port === 465;

  if (host) {
    // Custom SMTP (Brevo / Zoho / Custom Domain)
    return nodemailer.createTransport({
      host,
      port,
      secure,
      auth: { user, pass },
      tls: { rejectUnauthorized: false },
    });
  }

  if (user && pass) {
    // High-performance Gmail Direct SSL (Port 465)
    return nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: { user, pass },
      tls: { rejectUnauthorized: false },
    });
  }

  // Fallback / Mock transporter for development when password is not yet configured
  return null;
};

// Base HTML Template wrapper
const wrapHtmlTemplate = ({ title, subtitle, contentHtml, actionButton }) => {
  const fromName = process.env.EMAIL_SOCIETY_NAME || 'Mahadev Co-operative (T&C) Society Ltd.';
  const tagline = 'Himachal Pradesh State Electricity Board Ltd. (HPSEBL)';
  const currentYear = new Date().getFullYear();

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
      body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; background-color: #f1f5f9; color: #1e293b; line-height: 1.6; }
      .container { max-width: 600px; margin: 24px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }
      .header { background: linear-gradient(135deg, #0b192c 0%, #1e3a8a 50%, #1e1b4b 100%); padding: 32px 24px; text-align: center; color: #ffffff; }
      .header h1 { margin: 0; font-size: 20px; font-weight: 800; letter-spacing: 0.5px; color: #ffffff; text-transform: uppercase; }
      .header p { margin: 6px 0 0; font-size: 12px; color: #fef08a; font-weight: 600; letter-spacing: 0.3px; }
      .banner { background: #f8fafc; border-bottom: 2px solid #e2e8f0; padding: 16px 24px; }
      .banner h2 { margin: 0; font-size: 17px; color: #0f172a; font-weight: 700; }
      .banner p { margin: 4px 0 0; font-size: 13px; color: #64748b; }
      .content { padding: 28px 24px; font-size: 14px; color: #334155; }
      .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 18px 0; }
      .table-data { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
      .table-data td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
      .table-data td.label { color: #64748b; font-weight: 600; width: 45%; }
      .table-data td.val { color: #0f172a; font-weight: 700; text-align: right; }
      .highlight-badge { display: inline-block; background: #ecfdf5; color: #059669; border: 1px solid #a7f3d0; padding: 4px 12px; border-radius: 20px; font-weight: 700; font-size: 13px; }
      .btn { display: inline-block; background: linear-gradient(135deg, #0284c7 0%, #0369a1 100%); color: #ffffff !important; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: 700; font-size: 14px; text-align: center; margin: 20px 0 10px; box-shadow: 0 4px 12px rgba(2, 132, 199, 0.3); }
      .footer { background: #0f172a; padding: 24px; text-align: center; font-size: 11px; color: #94a3b8; line-height: 1.5; }
      .footer p { margin: 4px 0; }
      .footer a { color: #38bdf8; text-decoration: none; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>${fromName}</h1>
        <p>🏛️ ${tagline}</p>
      </div>

      <div class="banner">
        <h2>${title}</h2>
        ${subtitle ? `<p>${subtitle}</p>` : ''}
      </div>

      <div class="content">
        ${contentHtml}

        ${actionButton ? `
          <div style="text-align: center; margin-top: 24px;">
            <a href="${actionButton.url}" class="btn" target="_blank">${actionButton.text}</a>
          </div>
        ` : ''}
      </div>

      <div class="footer">
        <p><strong>Mahadev Co-operative (Thrift & Credit) Society Ltd.</strong></p>
        <p>HPSEBL Complex, Shimla, Himachal Pradesh | Helpline: support@mahadevsociety.com</p>
        <p style="margin-top: 10px; color: #64748b; font-size: 10px;">
          This is an automated transactional message generated by the SACCO Portal for registered members. Please do not reply directly to this automated email.
        </p>
      </div>
    </div>
  </body>
  </html>
  `;
};

// Generic Send Function
const sendEmail = async ({ to, subject, html, text }) => {
  const fromAddress = process.env.EMAIL_FROM || `"Mahadev Co-operative Society" <${process.env.EMAIL_USER || 'mahadevsociety2026@gmail.com'}>`;

  if (!to) {
    console.warn('⚠️ Email send skipped: No recipient email address provided.');
    return { success: false, message: 'No recipient email provided.' };
  }

  const transporter = getTransporter();

  if (!transporter) {
    console.log('\n📧 [MOCK EMAIL DISPATCH - Configure EMAIL_PASS in .env to send live]');
    console.log(`To: ${to}`);
    console.log(`Subject: ${subject}`);
    console.log('-------------------------------------------------------------\n');
    return { success: true, mock: true, message: 'Email logged in mock mode (SMTP credentials pending in .env).' };
  }

  try {
    const info = await transporter.sendMail({
      from: fromAddress,
      to,
      subject,
      text: text || subject,
      html,
    });
    console.log(`✅ Automated Email sent successfully to ${to} (Message ID: ${info.messageId})`);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error(`❌ Email dispatch error to ${to}:`, error.message);
    return { success: false, error: error.message };
  }
};

// ── 1. WELCOME & ACCOUNT APPROVAL EMAIL ──
const sendWelcomeApprovalEmail = async ({ to, name, vendorNo, designation, loginUrl = 'http://localhost:3000/#/login' }) => {
  const title = '🎉 Welcome to Mahadev Co-operative Society!';
  const subtitle = 'Your membership account access has been approved.';

  const contentHtml = `
    <p>Dear <strong>${name || 'Member'}</strong>,</p>
    <p>We are pleased to inform you that your registration with <strong>Mahadev Co-operative (T&C) Society Ltd.</strong> has been verified and approved by the administration.</p>
    
    <div class="card">
      <div style="font-weight: 700; margin-bottom: 8px; color: #0284c7;">📋 Your Membership Credentials:</div>
      <table class="table-data">
        <tr><td class="label">Member Name</td><td class="val">${name}</td></tr>
        <tr><td class="label">Vendor / Employee No</td><td class="val"><span class="highlight-badge">${vendorNo}</span></td></tr>
        ${designation ? `<tr><td class="label">Designation</td><td class="val">${designation}</td></tr>` : ''}
        <tr><td class="label">Account Status</td><td class="val" style="color: #059669;">Active & Verified</td></tr>
      </table>
    </div>

    <p>You can now log in to the portal using your <strong>Vendor Number (${vendorNo})</strong> and the password you set during registration to view your Share Capital, Monthly RD Passbook, and apply for Loans.</p>
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: { text: '🔐 Log In to Member Portal', url: loginUrl },
  });

  return sendEmail({
    to,
    subject: `🎉 Account Approved - Mahadev Co-operative Society (Vendor No: ${vendorNo})`,
    html,
  });
};

// ── 2. PASSWORD RESET EMAIL ──
const sendPasswordResetEmail = async ({ to, name, otpCode, resetUrl }) => {
  const title = '🔐 Security Notice: Password Reset Request';
  const subtitle = 'Verification code to reset your SACCO portal password.';

  const contentHtml = `
    <p>Dear <strong>${name || 'Member'}</strong>,</p>
    <p>We received a request to reset your password for the Mahadev Co-operative Society portal.</p>
    
    <div style="text-align: center; margin: 24px 0;">
      <div style="font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Your One-Time Verification Code (OTP):</div>
      <div style="font-size: 32px; font-weight: 800; letter-spacing: 6px; color: #0284c7; margin: 10px 0; background: #e0f2fe; padding: 12px 24px; border-radius: 8px; display: inline-block; border: 1px dashed #0284c7;">
        ${otpCode}
      </div>
      <div style="font-size: 12px; color: #ef4444; font-weight: 600;">⏰ Valid for 15 minutes only. Do not share this code with anyone.</div>
    </div>

    <p>If you did not make this request, please ignore this email or notify the society helpdesk immediately.</p>
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: resetUrl ? { text: 'Reset Password', url: resetUrl } : null,
  });

  return sendEmail({
    to,
    subject: `🔐 Password Reset OTP: ${otpCode} - Mahadev Society`,
    html,
  });
};

// ── 3. LOAN SANCTION & DISBURSEMENT EMAIL ──
const sendLoanSanctionEmail = async ({
  to,
  name,
  vendorNo,
  loanId,
  loanAmount,
  emiAmount,
  tenure,
  interestRate = 10,
  disbursementDate,
  portalUrl = 'http://localhost:3000/#/financials/loans',
}) => {
  const formattedAmount = Number(loanAmount || 0).toLocaleString('en-IN');
  const formattedEmi = Number(emiAmount || 0).toLocaleString('en-IN');
  const title = '🏦 Loan Sanction & Disbursement Advice';
  const subtitle = `Loan Account #${loanId || 'Active Loan'}`;

  const contentHtml = `
    <p>Dear <strong>${name || 'Member'}</strong>,</p>
    <p>Congratulations! Your loan application has been approved and sanctioned by the Society Board of Directors.</p>

    <div class="card">
      <div style="font-weight: 700; margin-bottom: 8px; color: #0284c7;">💳 Loan Particulars:</div>
      <table class="table-data">
        <tr><td class="label">Loan Account No</td><td class="val">${loanId || 'N/A'}</td></tr>
        <tr><td class="label">Sanctioned Principal</td><td class="val" style="color: #059669; font-size: 15px;">₹ ${formattedAmount}</td></tr>
        <tr><td class="label">Monthly EMI Amount</td><td class="val" style="color: #0284c7;">₹ ${formattedEmi} / month</td></tr>
        <tr><td class="label">Repayment Tenure</td><td class="val">${tenure} Months</td></tr>
        <tr><td class="label">Annual Interest Rate</td><td class="val">${interestRate}% per annum</td></tr>
        ${disbursementDate ? `<tr><td class="label">Disbursement Date</td><td class="val">${new Date(disbursementDate).toLocaleDateString('en-IN')}</td></tr>` : ''}
      </table>
    </div>

    <p>Monthly EMI deductions will be routed through your HPSEBL departmental salary payroll. You can track your real-time outstanding balance and amortization schedule on the portal.</p>
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: { text: '📊 View Loan Passbook', url: portalUrl },
  });

  return sendEmail({
    to,
    subject: `🏦 Loan Sanctioned: ₹${formattedAmount} (A/C: ${loanId}) - Mahadev Society`,
    html,
  });
};

// ── 4. MONTHLY EMI & DEPOSIT RECEIPT EMAIL ──
const sendMonthlyReceiptEmail = async ({
  to,
  name,
  vendorNo,
  monthYear,
  shareAmount = 0,
  rdAmount = 0,
  emiAmount = 0,
  remainingLoan = 0,
  rdBalance = 0,
  portalUrl = 'http://localhost:3000/#/financials/shares-savings',
}) => {
  const totalDeduction = Number(shareAmount) + Number(rdAmount) + Number(emiAmount);
  const title = `🧾 Monthly Society Credit Receipt (${monthYear})`;
  const subtitle = `Deduction Acknowledgement for Vendor No: ${vendorNo}`;

  const contentHtml = `
    <p>Dear <strong>${name || 'Member'}</strong>,</p>
    <p>Your monthly society contribution for the billing cycle <strong>${monthYear}</strong> has been successfully credited to your accounts:</p>

    <div class="card">
      <table class="table-data">
        <tr><td class="label">Share Capital Contribution</td><td class="val">₹ ${Number(shareAmount).toLocaleString('en-IN')}</td></tr>
        <tr><td class="label">Recurring Deposit (RD)</td><td class="val">₹ ${Number(rdAmount).toLocaleString('en-IN')}</td></tr>
        ${emiAmount > 0 ? `<tr><td class="label">Loan EMI Repayment</td><td class="val">₹ ${Number(emiAmount).toLocaleString('en-IN')}</td></tr>` : ''}
        <tr style="border-top: 2px solid #cbd5e1;"><td class="label" style="font-size: 14px;">Total Cleared Amount</td><td class="val" style="font-size: 15px; color: #0284c7;">₹ ${totalDeduction.toLocaleString('en-IN')}</td></tr>
      </table>
    </div>

    <div class="card" style="background: #ecfdf5; border-color: #a7f3d0;">
      <div style="font-weight: 700; color: #065f46; margin-bottom: 6px;">📈 Updated Account Balances:</div>
      <table class="table-data">
        <tr><td class="label" style="color: #047857;">Total Accumulated RD</td><td class="val" style="color: #065f46;">₹ ${Number(rdBalance).toLocaleString('en-IN')}</td></tr>
        ${remainingLoan > 0 ? `<tr><td class="label" style="color: #b91c1c;">Remaining Loan Balance</td><td class="val" style="color: #b91c1c;">₹ ${Number(remainingLoan).toLocaleString('en-IN')}</td></tr>` : ''}
      </table>
    </div>
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: { text: '📄 Download Monthly Statement', url: portalUrl },
  });

  return sendEmail({
    to,
    subject: `🧾 Monthly Society Receipt: ₹${totalDeduction.toLocaleString('en-IN')} (${monthYear}) - Mahadev Society`,
    html,
  });
};

// ── 5. HELPDESK TICKET REPLY EMAIL ──
const sendHelpdeskReplyEmail = async ({
  to,
  name,
  ticketNo,
  subject,
  userMessage,
  adminReply,
  adminName = 'Society Helpdesk',
  portalUrl = 'http://localhost:3000/#/communication/helpdesk',
}) => {
  const title = `💬 Update on Query #${ticketNo}`;
  const subtitle = subject || 'Member Support Ticket Response';

  const contentHtml = `
    <p>Dear <strong>${name || 'Member'}</strong>,</p>
    <p>The Society Administration has reviewed and replied to your support inquiry:</p>

    <div class="card" style="background: #f0fdf4; border-left: 4px solid #10b981;">
      <div style="font-size: 12px; color: #047857; font-weight: 700; text-transform: uppercase; margin-bottom: 4px;">Admin Response:</div>
      <div style="color: #0f172a; font-size: 14px; white-space: pre-wrap;">${adminReply}</div>
      <div style="font-size: 11px; color: #64748b; margin-top: 8px;">— Responded by <strong>${adminName}</strong></div>
    </div>

    ${userMessage ? `
      <div style="margin-top: 16px; padding: 12px; background: #f8fafc; border-radius: 6px; font-size: 12px; color: #64748b;">
        <strong>Your Original Message:</strong> "${userMessage}"
      </div>
    ` : ''}
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: { text: '💬 View Full Conversation', url: portalUrl },
  });

  return sendEmail({
    to,
    subject: `💬 Query #${ticketNo} Update: ${subject || 'Helpdesk Reply'} - Mahadev Society`,
    html,
  });
};

// ── 6. TEST EMAIL DISPATCH ──
const sendTestEmail = async ({ to }) => {
  const title = '⚡ SMTP Test Notification';
  const subtitle = 'Mahadev Co-operative Society Email Engine';
  const now = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const contentHtml = `
    <p>Hello Admin,</p>
    <p>This is a test notification confirming that the <strong>Automated Email Notification System</strong> for <strong>Mahadev Co-operative (T&C) Society Ltd.</strong> is functioning properly.</p>

    <div class="card">
      <table class="table-data">
        <tr><td class="label">SMTP Gateway</td><td class="val">${process.env.SMTP_HOST || 'Gmail / App Password'}</td></tr>
        <tr><td class="label">Sender Address</td><td class="val">${process.env.EMAIL_USER || 'mahadevsociety2026@gmail.com'}</td></tr>
        <tr><td class="label">Timestamp</td><td class="val">${now}</td></tr>
        <tr><td class="label">Status</td><td class="val" style="color: #059669;">✅ Operational & Verified</td></tr>
      </table>
    </div>

    <p>All automated triggers (Registration Approvals, Loan Sanction receipts, Monthly EMI debits, and Helpdesk responses) are connected and ready.</p>
  `;

  const html = wrapHtmlTemplate({
    title,
    subtitle,
    contentHtml,
    actionButton: { text: '🏛️ Open Society Portal', url: 'http://localhost:3000' },
  });

  return sendEmail({
    to,
    subject: `⚡ SMTP Connection Test - Mahadev Co-operative Society (${now})`,
    html,
  });
};

// ── 7. VERIFY CONNECTION HEALTH ──
const verifyEmailConfig = async () => {
  const transporter = getTransporter();
  if (!transporter) {
    return { configured: false, message: 'SMTP credentials pending in .env (Mock mode active).' };
  }
  try {
    await transporter.verify();
    return { configured: true, message: 'SMTP Gateway connected and ready.' };
  } catch (err) {
    return { configured: false, error: err.message };
  }
};

module.exports = {
  sendEmail,
  sendWelcomeApprovalEmail,
  sendPasswordResetEmail,
  sendLoanSanctionEmail,
  sendMonthlyReceiptEmail,
  sendHelpdeskReplyEmail,
  sendTestEmail,
  verifyEmailConfig,
};
